services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: ecommerce-nginx-lb
    ports:
      - "80:80"
    depends_on:
      - app1
      - app2

  app1:
    build: .
    hostname: app1
    container_name: ecommerce-app-1
    depends_on:
      - mysql-ds-master
      - mysql-ds-slave
      - redis
      - rabbitmq
    ports:
      - "8081:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USER: mq_user
      SPRING_RABBITMQ_PASS: mq_password
    restart: unless-stopped

  app2:
    build: .
    hostname: app2
    container_name: ecommerce-app-2
    depends_on:
      - mysql-ds-master
      - mysql-ds-slave
      - redis
      - rabbitmq
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_RABBITMQ_HOST: rabbitmq
      SPRING_RABBITMQ_PORT: 5672
      SPRING_RABBITMQ_USER: mq_user
      SPRING_RABBITMQ_PASS: mq_password
    restart: unless-stopped

  redis:
    image: redis:7.2
    container_name: ecommerce-redis
    ports:
      - "6379:6379"
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  environment:
    RABBITMQ_DEFAULT_USER: mq_user
    RABBITMQ_DEFAULT_PASS: mq_password
    RABBITMQ_DEFAULT_VHOST: /

  # 分片 ds – Master
  mysql-ds-master:
    image: mysql:8.0
    container_name: ecommerce-mysql-ds-master
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    command: >
      --server-id=101
      --log-bin=mysql-bin
      --binlog-format=ROW
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - db_ds_master_data:/var/lib/mysql
      - ./mysql-init/ds-master:/docker-entrypoint-initdb.d

  # 分片 ds – Slave
  mysql-ds-slave:
    image: mysql:8.0
    container_name: ecommerce-mysql-ds-slave
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: app_user
      MYSQL_PASSWORD: app_pass
    command: >
      --server-id=102
      --relay-log=relay-log
      --log-bin=mysql-bin
      --read-only=1
      --gtid-mode=ON
      --enforce-gtid-consistency=ON
      --default-authentication-plugin=mysql_native_password
    depends_on:
      - mysql-ds-master
    ports:
      - "3307:3306"
    volumes:
      - db_ds_slave_data:/var/lib/mysql
      - ./mysql-init/ds-slave:/docker-entrypoint-initdb.d

volumes:
  db_ds_master_data:
  db_ds_slave_data: