server:
  port: 8080

spring:
  application:
    name: ecommerce-demo
  profiles:
    active: dev

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ecommerce.model
  configuration:
    map-underscore-to-camel-case: true

