spring:
  datasource:
    url: jdbc:dummy      # 占位，不再用 shardingsphere driver
    driver-class-name: com.mysql.cj.jdbc.Driver

  # Redis
  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

