spring:
  datasource:
    driver-class-name: org.apache.shardingsphere.driver.ShardingSphereDriver
    url: jdbc:shardingsphere:classpath:sharding-dev.yml

  data:
    redis:
      host: localhost
      port: 6379

  rabbitmq:
    virtual-host: /
    host: localhost
    port: 5672
    username: mq_user
    password: mq_password

mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    com.example.ecommerce: DEBUG