server:
  port: 8080

spring:
  application:
    name: ecommerce-demo

  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/ecommerce?useSSL=false&serverTimezone=UTC&characterEncoding=utf8
    username: user
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

    # Druid specific settings below
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

      # enable monitoring dashboard
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: admin123
        url-pattern: /druid/*

      # enable SQL/web statistics
      web-stat-filter:
        enabled: true
        exclusions: "*.js,*.css,/druid/*"

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.ecommerce.model
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com.example.ecommerce: DEBUG